[package]
name = "lyon_path"
version = "0.3.2"
description = "A simple and optional path data structure that can be used with the rest of the lyon crates."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/lyon"
documentation = "https://nical.github.io/lyon-doc/lyon_path/"
license = "MIT/Apache-2.0"

[lib]
name = "lyon_path"

[dependencies]
lyon_core = { version = "0.3.2", path = "../core" }
lyon_bezier = { version = "0.3.2", path = "../bezier" }
lyon_path_builder = { version = "0.3.2", path = "../path_builder" }
lyon_path_iterator = { version = "0.3.2", path = "../path_iterator" }
