[package]

name = "io"
version = "0.1.0"
authors = [
    "Nicolas Silva <nical.silva@gmail.com>",
]

[[lib]]
name = "io"
path = "./lib.rs"

[dependencies.data]
path = "../data/"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs.git"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
