[workspace]
members = [
    "crates/lyon",
    "crates/path",
    "crates/tessellation",
    "crates/algorithms",
    "crates/tess2",
    "crates/geom",
    "crates/extra",
    "crates/svg",
    "cli",
    "wasm_test",
    "examples/wgpu",
    "examples/wgpu_svg",
    "bench/tess",
    "bench/path",
    "bench/geom"
]

exclude = [
    ".vscode/*",
    "all.sh",
    "assets/*",
    "examples/*",
    "bench/*",
    "cli/*",
]

# Uncomment this when profiling.
#[profile.release]
#debug = true
