[package]

name = "lyon"
version = "0.8.6"
description = "2D Graphics rendering on the GPU using tessellation."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/lyon"
documentation = "https://docs.rs/lyon/"
keywords = ["2d", "graphics", "tessellation", "svg"]
license = "MIT/Apache-2.0"

exclude = [
    "assets/*",
    "examples/*",
    "bench/*",
    "cli/*",
    ".vscode/*",
    "all.sh"
]

[lib]
name = "lyon"
path = "src/lib.rs"

# Uncomment this when profiling.
#[profile.release]
#debug = true

[dependencies]

lyon_tessellation = { version = "0.8.6", path = "tessellation/" }
lyon_extra = { version = "0.8.6", path = "extra/" }
lyon_svg = { version = "0.8.6", path = "svg/" }

[workspace]
members = [
    "path",
    "tessellation",
    "geom",
    "extra",
    "svg",
    "cli",
    "examples/gfx_advanced",
    "examples/gfx_basic",
    "examples/intersections",
    "examples/svg_viewer",
    "bench/svg_bench",
    "bench/tess"
]
