[package]

name = "lyon"
version = "0.16.2"
description = "2D Graphics rendering on the GPU using tessellation."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/lyon"
documentation = "https://docs.rs/lyon/"
keywords = ["2d", "graphics", "tessellation", "svg"]
license = "MIT/Apache-2.0"

exclude = [
    "assets/*",
    "examples/*",
    "bench/*",
    "cli/*",
    ".vscode/*",
    "all.sh"
]

[lib]
name = "lyon"
path = "src/lib.rs"

# Uncomment this when profiling.
#[profile.release]
#debug = true

[features]
serialization = ["lyon_tessellation/serialization"]
debugger = ["lyon_tessellation/debugger"]
experimental = ["lyon_tessellation/experimental"]
svg = ["lyon_svg"]
extra = ["lyon_extra"]
libtess2 = ["lyon_tess2"]

[dependencies]

lyon_tessellation = { version = "0.16.1", path = "tessellation/" }
lyon_algorithms = { version = "0.16", path = "algorithms/" }
lyon_extra = { version = "0.16", optional = true, path = "extra/" }
lyon_svg = { version = "0.16.0", optional = true, path = "svg/" }
lyon_tess2 = { version = "0.16.0", optional = true, path = "tess2/" }

[workspace]
members = [
    "path",
    "tessellation",
    "algorithms",
    "tess2",
    "geom",
    "extra",
    "svg",
    "cli",
    "wasm_test",
    "examples/wgpu",
    "examples/wgpu_svg",
    "examples/walk_path",
    "bench/tess",
    "bench/path",
    "bench/geom"
]
