[package]
name = "wgpu-example"
version = "0.1.0"
authors = ["Nicolas Silva <nical@fastmail.com>"]
workspace = "../.."
edition = "2018"

[[bin]]
name = "wgpu"
path = "src/main.rs"

[dependencies]
lyon = { path = "../../", features = ["extra"] }
env_logger = "0.7"
log = "0.4"

wgpu = "0.4"
wgpu-native = "0.4"
winit = "0.20.0-alpha4"
