[package]
name = "lyon_cli"
version = "0.1.0"
authors = ["Nicolas Silva <nical@fastmail.com>"]
workspace = ".."

[[bin]]
name = "lyon"

[dependencies]
lyon = { path = "../" }
lyon_extra = { path = "../extra" }
clap = "2.19.2"

