[package]
name = "svg_render"
description = "A simple svg renderer based on resvg"
version = "0.1.0"
authors = ["Roland Kovacs <zen3ger@gmail.com>"]
workspace = "../.."

[[bin]]
name = "svg_render"
path = "src/main.rs"

[dependencies]
lyon = { path = "../../", features = ["extra"] }

gfx = "0.17.1"
gfx_device_gl = "0.15.0"
gfx_window_glutin = "0.20.0"
glutin = "0.12.0"
resvg = "0.2"
