[package]

name = "lyon_tessellation"
version = "0.8.4"
description = "A low level path tessellation library."
authors = [ "Nicolas Silva <nical@fastmail.com>" ]
repository = "https://github.com/nical/lyon"
documentation = "https://docs.rs/lyon_tessellation/"
keywords = ["2d", "graphics", "tessellation", "svg"]
license = "MIT/Apache-2.0"
workspace = ".."

[lib]
name = "lyon_tessellation"
path = "src/lib.rs"

[dependencies]

lyon_core = { version = "0.8.0", path = "../core" }
lyon_path = { version = "0.8.0", path = "../path" }
lyon_bezier = { version = "0.8.4", path = "../bezier" }
lyon_path_builder = { version = "0.8.0", path = "../path_builder" }
lyon_path_iterator = { version = "0.8.0", path = "../path_iterator" }
sid = "0.5"

[dev-dependencies]
lyon_extra = { version = "0.8.1", path = "../extra" }
