[package]
name = "vertex_aa_example"
version = "0.0.1"
authors = ["Nicolas Silva <nical.silva@gmail.com>"]

[[bin]]
name = "vertex_aa_example"
path = "./main.rs"

[dependencies.gl]
git = "https://github.com/bjz/gl-rs"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs"

[dependencies.data]
path = "../../data/"

[dependencies.math]
path = "../../math/"

[dependencies.gpu]
path = "../../gpu/"

[dependencies.gfx2d]
path = "../../gfx2d/"
